FROM python:3.9-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagit \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml .env $DAGSTER_HOME

WORKDIR $DAGSTER_HOME