services:

  docker_postgresql:
    image: postgres:11
    container_name: docker_postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - docker_network

  docker_user_code:
    build:
      context: .
      dockerfile: ./Dockerfile_user
    container_name: docker_user_code
    image: docker_user_code_image
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MOTHERDUCK_PATH: ${MOTHERDUCK_PATH}
      DAGSTER_CURRENT_IMAGE: "docker_user_code_image"
    env_file:
      - .env
    expose:
      - 4002
    networks:
      - docker_network

  docker_data_generators:
    build:
      context: .
      dockerfile: ./Dockerfile_data_generators
      args: 
        - MOTHERDUCK_PATH_ARG=${MOTHERDUCK_PATH}
    container_name: docker_data_generators
    image: docker_data_generators_image
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MOTHERDUCK_PATH: ${MOTHERDUCK_PATH}
      DAGSTER_CURRENT_IMAGE: "docker_data_generators_image"
    env_file:
      - .env
    expose:
      - 4001
    networks:
      - docker_network

  docker_simulated_source_system:
    build:
      context: .
      dockerfile: ./Dockerfile_simulated_source_system
    container_name: docker_simulated_source_system
    image: docker_simulated_source_system_image
    restart: always
    environment:
      MOTHERDUCK_PATH: ${MOTHERDUCK_PATH}
      DAGSTER_CURRENT_IMAGE: "docker_simulated_source_system_image"
    env_file:
      - .env
    volumes:
      - /duckster.duckdb:/simulated_source_system/duckster.duckdb
    expose:
      - 4003
    networks:
      - docker_network


  docker_dagster_ui:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: docker_dagster_ui
    image: docker_dagster_ui_image
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_network
    depends_on:
      - docker_user_code
      - docker_data_generators
      - docker_postgresql

  docker_daemon:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: docker_daemon
    image: docker_daemon_image
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_network
    depends_on:
      - docker_user_code
      - docker_data_generators
      - docker_postgresql

volumes: 
  pgdata:

networks:
  docker_network:
    driver: bridge
    name: docker_network