FROM python:3.9-slim

ENV DAGSTER_HOME=/opt/dagster/dagster_home/
ENV DAGSTER_CWD=/opt/dagster/app/
WORKDIR ${DAGSTER_CWD}

RUN mkdir -p $DAGSTER_HOME


COPY dagster.yaml ${DAGSTER_CWD}
COPY workspace.yaml ${DAGSTER_CWD}
COPY location_data_generators/requirements.txt ${DAGSTER_CWD}
RUN pip install -r requirements.txt
COPY location_data_generators ${DAGSTER_CWD}/location_data_generators
COPY dbt_transformations ${DAGSTER_CWD}/dbt_transformations


RUN dbt compile --project-dir ./dbt_transformations --profiles-dir ./dbt_transformations/config
EXPOSE 4001

CMD ["dagster", "api", "grpc", "-f", "./location_data_generators/definitions.py", "-h", "0.0.0.0", "-p", "4001"]