FROM python:3.9-slim

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml requirements.txt .env $DAGSTER_HOME

WORKDIR $DAGSTER_HOME

RUN pip install -r requirements.txt