dbt_transformations:
  target: motherduck
  outputs:
    local:
      type: duckdb
      path: duckster
      schema: duckster
    motherduck:
      type: duckdb
      path: "{{ env_var('MOTHERDUCK_PATH') }}"
      schema: duckster
